global:
  domain: cd.audacioustux.com
  addPrometheusAnnotations: true
  priorityClassName: system-cluster-critical
server:
  ingress:
    enabled: true
    annotations:
      ingress.cilium.io/tls-passthrough: enabled
      ingress.cilium.io/force-https: enabled
    tls: true
  metrics:
    enabled: true
controller:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true
redis:
  metrics:
    enabled: true
applicationSet:
  metrics:
    enabled: true
notifications:
  metrics:
    enabled: true
dex:
  enabled: false
