apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: &name mimir-ruler-bucket
  namespace: monitoring
spec:
  bucketName: *name
  storageClassName: rook-ceph-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: &name mimir-blocks-bucket
  namespace: monitoring
spec:
  bucketName: *name
  storageClassName: rook-ceph-bucket