prometheus:
  enabled: true
dashboards:
  enabled: true
hubble:
  enabled: true
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
    dashboards:
      enabled: true
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 6443
k8sClientRateLimit:
  qps: 50
  burst: 100
ingressController:
  default: true
  enabled: true
  loadbalancerMode: shared
  enforceHttps: false
gatewayAPI:
  enabled: true
bpf:
  datapathMode: netkit
  masquerade: true
ipv6:
  enabled: false # TODO: Enable after troubleshooting
routingMode: native
ipv4NativeRoutingCIDR: 10.42.0.0/16
ipv6NativeRoutingCIDR: 2001:cafe:42::/56
localRedirectPolicy: true
enableIPv4BIGTCP: true
enableIPv6BIGTCP: true
bandwidthManager:
  enabled: true
  bbr: true
loadBalancer:
  mode: hybrid
  algorithm: maglev
  acceleration: best-effort
nodeIPAM:
  enabled: true
defaultLBServiceIPAM: nodeipam
operator:
  replicas: 1
  rollOutPods: true
  prometheus:
    enabled: true
  dashboards:
    enabled: true
rollOutCiliumPods: true
envoy:
  enabled: true
  rollOutPods: true