kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 6443
ingressController:
  default: true
  enabled: true
  loadbalancerMode: shared
  enforceHttps: false
gatewayAPI:
  enabled: true
bpf:
  datapathMode: netkit
  masquerade: true
ipv6: 
  enabled: true
routingMode: native
ipv4NativeRoutingCIDR: 10.42.0.0/16
ipv6NativeRoutingCIDR: 2001:cafe:42::/56
localRedirectPolicy: true
enableIPv4BIGTCP: true
enableIPv6BIGTCP: true
bandwidthManager:
  enabled: true
  bbr: true
hubble:
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
nodeIPAM:
  enabled: true
defaultLBServiceIPAM: nodeipam
operator:
  replicas: 1
  rollOutPods: true
rollOutCiliumPods: true
debug:
  enabled: true
  verbose: flow
envoy:
  enabled: true
  rollOutPods: true
