apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubeplane
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
