apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: &project kubeplane
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - metadata:
              name: vertical-pod-autoscaler
            spec:
              source:
                repoURL: ghcr.io/stevehipwell/helm-charts
                chart: vertical-pod-autoscaler
                targetRevision: ~1.8.0
              destination:
                namespace: vpa
          
          - metadata:
              name: cert-manager
            spec:
              source:
                repoURL: https://charts.jetstack.io
                chart: cert-manager
                targetRevision: ~1.17.0
                helm:
                  valuesObject:
                    crds:
                      enabled: true
              destination:
                namespace: cert-manager
          
          - metadata:
              name: kyverno
            spec:
              source:
                repoURL: https://kyverno.github.io/kyverno
                chart: kyverno
                targetRevision: ~3.3.0
              destination:
                namespace: kyverno
          
          - metadata:
              name: keda
            spec:
              source:
                repoURL: https://kedacore.github.io/charts
                chart: keda
                targetRevision: ~2.16.0
              destination:
                namespace: keda
          
          - metadata:
              name: redis-operator
            spec:
              source:
                repoURL: https://ot-container-kit.github.io/helm-charts
                chart: redis-operator
                targetRevision: ~0.19.0
              destination:
                namespace: redis
          
          - metadata:
              name: cloudnative-pg
            spec:
              source:
                repoURL: https://cloudnative-pg.github.io/charts
                chart: cloudnative-pg
                targetRevision: ~0.23.0
              destination:
                namespace: pg
          
          - metadata:
              name: scylla-operator
            spec:
              source:
                repoURL: https://scylla-operator-charts.storage.googleapis.com/stable
                chart: scylla-operator
                targetRevision: ~1.16.0
                helm:
                  valuesObject:
                    replicas: 1
                    webhookServerReplicas: 1
              destination:
                namespace: scylla-operator
          
          - metadata:
              name: minio-operator
            spec:
              source:
                repoURL: https://operator.min.io
                chart: operator
                targetRevision: ~7.0.0
              destination:
                namespace: minio
          
          - metadata:
              name: rancher
            spec:
              source:
                repoURL: https://releases.rancher.com/server-charts/stable
                chart: rancher
                targetRevision: ~2.10.0
                helm:
                  kubeVersion: 1.31.0
                  valuesObject:
                    replicas: 1
                    hostname: dash.audacioustux.com
                    ingress:
                      pathType: Prefix
              destination:
                namespace: cattle-system
          
          - metadata:
              name: rook-ceph
            spec:
              source:
                repoURL: https://charts.rook.io/release
                chart: rook-ceph
                targetRevision: ~1.16.0
              destination:
                namespace: rook-ceph
          
          - metadata:
              name: cilium
            spec:
              source:
                repoURL: https://helm.cilium.io
                chart: cilium
                targetRevision: ~1.17.0
                helm:
                  valuesObject:
                    kubeProxyReplacement: true
                    k8sServiceHost: localhost
                    k8sServicePort: 6443
                    ingressController:
                      default: true
                      enabled: true
                      loadbalancerMode: shared
                      enforceHttps: false
                    gatewayAPI:
                      enabled: true
                    bpf:
                      datapathMode: netkit
                      masquerade: true
                    ipv6:
                      enabled: true
                    routingMode: native
                    ipv4NativeRoutingCIDR: 10.42.0.0/16
                    ipv6NativeRoutingCIDR: 2001:cafe:42::/56
                    localRedirectPolicy: true
                    enableIPv4BIGTCP: true
                    enableIPv6BIGTCP: true
                    bandwidthManager:
                      enabled: true
                      bbr: true
                    loadBalancer:
                      mode: hybrid
                      algorithm: maglev
                      acceleration: best-effort
                    nodeIPAM:
                      enabled: true
                    defaultLBServiceIPAM: nodeipam
                    operator:
                      replicas: 1
                      rollOutPods: true
                    rollOutCiliumPods: true
                    envoy:
                      enabled: true
                      rollOutPods: true
              destination:
                namespace: kube-system
  
  template:
    metadata:
      name: "{{.metadata.name}}"
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
    spec:
      project: *project
      destination:
        server: https://kubernetes.default.svc
        namespace: *project
      syncPolicy:
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    {{- toYaml . }}

