dex:
  enabled: false
notifications:
  enabled: false
configs:
  params:
    server.insecure: true
global:
  domain: cd.audacioustux.com
server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
    tls: true
