apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubeplane
  source:
    repoURL: ghcr.io/argoproj/argo-helm
    chart: argo-cd
    targetRevision: ~7.8.0
    helm:
      valuesObject:
        global:
          domain: argocd.audacioustux.com
          addPrometheusAnnotations: true
          priorityClassName: system-cluster-critical
          networkPolicy:
            create: true
        server:
          ingress:
            enabled: true
            annotations:
              ingress.cilium.io/tls-passthrough: enabled
              ingress.cilium.io/force-https: enabled
            tls: true
          metrics:
            enabled: true
        controller:
          metrics:
            enabled: true
        repoServer:
          metrics:
            enabled: true
        redis:
          metrics:
            enabled: true
        applicationSet:
          metrics:
            enabled: true
        notifications:
          metrics:
            enabled: true
        dex:
          enabled: false
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - Validate=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m