apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubeplane
  source:
    repoURL: https://helm.cilium.io
    chart: cilium
    targetRevision: ~1.17.0
    helm:
      valuesObject:
        prometheus:
          enabled: true
        dashboards:
          enabled: true
        hubble:
          enabled: true
          metrics:
            enableOpenMetrics: true
            enabled:
              - dns
              - drop
              - tcp
              - flow
              - port-distribution
              - icmp
              - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
            dashboards:
              enabled: true
          relay:
            enabled: true
            rollOutPods: true
          ui:
            enabled: true
            rollOutPods: true
        kubeProxyReplacement: true
        k8sServiceHost: localhost
        k8sServicePort: 6443
        k8sClientRateLimit:
          qps: 50
          burst: 100
        ingressController:
          default: true
          enabled: true
          loadbalancerMode: shared
          enforceHttps: false
        gatewayAPI:
          enabled: true
        bpf:
          datapathMode: netkit
          masquerade: true
        ipv6:
          enabled: true
        routingMode: native
        ipv4NativeRoutingCIDR: 10.42.0.0/16
        ipv6NativeRoutingCIDR: 2001:cafe:42::/56
        localRedirectPolicy: true
        enableIPv4BIGTCP: true
        enableIPv6BIGTCP: true
        bandwidthManager:
          enabled: true
          bbr: true
        loadBalancer:
          mode: hybrid
          algorithm: maglev
          acceleration: best-effort
        nodeIPAM:
          enabled: true
        defaultLBServiceIPAM: nodeipam
        operator:
          replicas: 1
          rollOutPods: true
          prometheus:
            enabled: true
          dashboards:
            enabled: true
        rollOutCiliumPods: true
        envoy:
          enabled: true
          rollOutPods: true
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - Validate=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m