apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubeplane
  source:
    repoURL: https://coredns.github.io/helm
    chart: coredns
    targetRevision: ~1.39.0
    helm:
      valuesObject:
        service:
          clusterIP: 10.43.0.10
          clusterIPs:
            - 10.43.0.10
            - 2001:cafe:43::a
          ipFamilyPolicy: PreferDualStack
        priorityClassName: system-cluster-critical
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - Validate=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m