apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e2e-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubeplane
  sources:
  - repoURL: https://audacioustux.github.io/kubeplane
    chart: generic-helm
    targetRevision: "~1.0.0"
    helm:
      valuesObject:
        list:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: http-echo
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: http-echo
              template:
                metadata:
                  labels:
                    app: http-echo
                spec:
                  containers:
                    - name: http-echo
                      image: ghcr.io/mendhak/http-https-echo:35
                      ports:
                        - name: http
                          containerPort: 8080
                        - name: https
                          containerPort: 8433

          - apiVersion: v1
            kind: Service
            metadata:
              name: http-echo
            spec:
              selector:
                app: http-echo
              ports:
                - name: http
                  protocol: TCP
                  port: 80
                  targetPort: http
                - name: https
                  protocol: TCP
                  port: 443
                  targetPort: https

          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: http-echo
              annotations:
                cert-manager.io/cluster-issuer: selfsigned
            spec:
              ingressClassName: cilium
              tls:
                - hosts:
                    - d-ing.audacioustux.com
                  secretName: http-echo-ingress-tls
              rules:
                - host: d-ing.audacioustux.com
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: http-echo
                            port:
                              name: http

          # - apiVersion: gateway.networking.k8s.io/v1
          #   kind: Gateway
          #   metadata:
          #     name: http-echo-gateway
          #   spec:
          #     gatewayClassName: istio
          #     listeners:
          #       - name: http
          #         protocol: HTTP
          #         port: 80
          #       - name: https
          #         protocol: HTTPS
          #         port: 443
          #         tls:
          #           certificateRefs:
          #             - kind: Secret
          #               name: http-echo-gateway-tls

          # - apiVersion: gateway.networking.k8s.io/v1
          #   kind: HTTPRoute
          #   metadata:
          #     name: http-echo-route
          #   spec:
          #     parentRefs:
          #       - name: http-echo-gateway
          #     hostnames:
          #       - d-gw.audacioustux.com
          #     rules:
          #       - matches:
          #           - path:
          #               type: PathPrefix
          #               value: /
          #         backendRefs:
          #           - name: http-echo
          #             port: http

          # - apiVersion: gateway.networking.k8s.io/v1
          #   kind: TLSRoute
          #   metadata:
          #     name: http-echo-tls-route
          #   spec:
          #     parentRefs:
          #       - name: http-echo-gateway
          #     hostnames:
          #       - d-gw.audacioustux.com
          #     rules:
          #       - backendRefs:
          #           - name: http-echo
          #             port: https
  destination:
    namespace: dbg
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - Validate=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m