apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubeplane
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: ~8.10.0
    helm:
      valuesObject:
        adminPassword: "admin"
        ingress:
          enabled: true
          hosts:
            - grafana.audacioustux.com
          annotations:
            cert-manager.io/cluster-issuer: selfsigned
          tls:
            - secretName: grafana-tls
              hosts:
                - grafana.audacioustux.com
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Mimir
                type: prometheus
                url: http://mimir-nginx.monitoring.svc.cluster.local/prometheus
        sidecar:
          dashboards:
            enabled: true
            searchNamespace: ALL
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: ceph
                orgId: 1
                folder: ceph
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/ceph
        dashboards:
          ceph:
            cluster:
              gnetId: 2842
              datasource: Mimir
            osd:
              gnetId: 5336
              datasource: Mimir
            pool:
              gnetId: 5342
              datasource: Mimir
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - Validate=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
