apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubeplane
  source:
    repoURL: https://audacioustux.github.io/kubeplane
    chart: generic-helm
    targetRevision: "~1.0.0"
    helm:
      valuesObject:
        map:
          kubeplane-scale-vpa:
            apiVersion: kyverno.io/v1
            kind: ClusterPolicy
            spec:
              generateExisting: true
              useServerSideApply: true
              rules:
                - name: generate-vpa
                  match:
                    any:
                    - resources:
                        kinds:
                          - Deployment
                          - StatefulSet
                          - DaemonSet
                        annotations:
                          scale.kubeplane/vpa: "true"
                  generate:
                    apiVersion: autoscaling.k8s.io/v1
                    kind: VerticalPodAutoscaler
                    name: "{{request.object.metadata.name}}"
                    namespace: "{{request.object.metadata.namespace}}"
                    synchronize: true
                    data:
                      spec:
                        targetRef:
                          apiVersion: apps/v1
                          kind: "{{request.object.kind}}"
                          name: "{{request.object.metadata.name}}"
                        updatePolicy:
                          updateMode: "{{ lookup(request.object.metadata.annotations, 'scale.kubeplane/vpa-updateMode') || 'Auto' }}"
                          minReplicas: "{{ lookup(request.object.metadata.annotations, 'scale.kubeplane/vpa-minReplicas') || '1' | to_number(@) }}"
                        resourcePolicy:
                          containerPolicies:
                            - containerName: "*"
                              maxAllowed:
                                cpu: "{{ lookup(request.object.metadata.annotations, 'scale.kubeplane/vpa-maxCPU') || '0.1' }}"
                                memory: "{{ lookup(request.object.metadata.annotations, 'scale.kubeplane/vpa-maxMemory') || '8Gi' }}"
                              minAllowed:
                                cpu: "{{ lookup(request.object.metadata.annotations, 'scale.kubeplane/vpa-minCPU') || '0m' }}"
                                memory: "{{ lookup(request.object.metadata.annotations, 'scale.kubeplane/vpa-minMemory') || '0Mi' }}"
          kubeplane-global-scale-vpa:
            apiVersion: kyverno.io/v1
            kind: ClusterPolicy
            spec:
              rules:
                - name: mutate-namespaces
                  match:
                    any:
                    - resources:
                        kinds:
                          - Namespace
                  exclude:
                    any:
                    - resources:
                        annotations:
                          ns.scale.kubeplane/vpa.disabled: "true"
                  mutate:
                    patchStrategicMerge:
                      metadata:
                        annotations:
                          ns.scale.kubeplane/vpa: "true"
          kubeplane-ns-scale-vpa:
            apiVersion: kyverno.io/v1
            kind: ClusterPolicy
            spec:
              generateExisting: true
              useServerSideApply: true
              rules:
                - name: mutate-namespaces
                  match:
                    any:
                    - resources:
                        kinds:
                          - Namespace
                        annotations:
                          ns.scale.kubeplane/vpa: "true"
                  generate:
                    apiVersion: kyverno.io/v1
                    kind: Policy
                    name: kubeplane-ns-scale-vpa
                    namespace: "{{request.object.metadata.name}}"
                    synchronize: true
                    data:
                      spec:
                        rules:
                          - name: mutate-workloads
                            match:
                              any:
                              - resources:
                                  kinds:
                                    - Deployment
                                    - StatefulSet
                                    - DaemonSet
                            exclude:
                              any:
                              - resources:
                                  annotations:
                                    scale.kubeplane/vpa.disabled: "true"
                            mutate:
                              patchStrategicMerge:
                                metadata:
                                  annotations:
                                    scale.kubeplane/vpa: "true"
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - Validate=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

