apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubeplane
  sources:
  - repoURL: https://kyverno.github.io/kyverno
    chart: kyverno
    targetRevision: ~3.3.0
    helm:
      valuesObject:
        admissionController:
          priorityClassName: system-cluster-critical
        backgroundController:
          priorityClassName: system-cluster-critical
        cleanupController:
          priorityClassName: system-cluster-critical
        reportsController:
          priorityClassName: system-cluster-critical
        webhooksCleanup:
          autoDeleteWebhooks:
            enabled: true
  - repoURL: https://audacioustux.github.io/kubeplane
    chart: generic-helm
    targetRevision: "~1.0.0"
    helm:
      valuesObject:
        list:
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: kyverno:kubeplane-scale-vpa
            labels:
              rbac.kyverno.io/aggregate-to-admission-controller: "true"
              rbac.kyverno.io/aggregate-to-background-controller: "true"
          rules:
          - apiGroups:
            - autoscaling.k8s.io
            resources:
            - verticalpodautoscalers
            verbs: 
            - "*"
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - Validate=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

